# Generated by Django 3.2.3 on 2021-07-23 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210724_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='subject',
            new_name='zip',
        ),
    ]
