# Generated by Django 3.2.3 on 2021-07-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_subject_application_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='zip',
        ),
    ]
